### ISSUE TITLE
ld.so looks in wrong directory for analysis modules

### ISSUE THREAD

**Issue by otheus** [epam/nfstrace#16]
Is there any way to make the build process more harmonious with the RPM packaging process? The `cpack -G RPM` puts the shared analysis modules into `/usr/lib/nfstrace`, which one would expect on a RHEL system. But the cmake used the default `/usr/local` as a prefix. Can someone update the README so as to demonstrate how to make and configure such variables with cpack?

**Comment by otheus** [comment]
cmake absolutely confounds me. Wtf am I supposed to do with this? How can I do a global make clean? How do I "configure" the variables?

**Comment by otheus** [comment]
How can we get `CPACK_PACKAGE_FILE_NAME` to use the canonical `{name}-{major}.{minor}.{release}-{vendor}.{vendorrelease}-{arch}`?

**Comment by otheus** [comment]
Something is really wrong with how the CpackConfig.make file is configured. Options on the command line to cpack should override them. In the end, I hardcoded my values in `CPackConfig.cmake` but that seems like a Hack.

**Comment by pkarneliuk** [comment]
Hello,

> Can someone update the README so as to demonstrate how to make and configure such variables with cpack?

It is already in README.md. Please look at [this](https://github.com/epam/nfstrace/blame/master/README.md#L69-L71). Also, you can prepare a pull request with your changes.

> How can we get CPACK_PACKAGE_FILE_NAME to use the canonical

[cpack documentation](https://cmake.org/cmake/help/v3.0/module/CPack.html) says that you should override next options: ${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION} ${CPACK_SYSTEM_NAME}. They may be specified during configuration step. 

>`cpack -G RPM -R 2 --vendor UIBK` should work, but no.

My patch 89bcc1c fixes hard-coded vendor property of rpm file and updates links in README.md. Now you can override vendor from command line option. The default value is the same "EPAM Systems" as before.

**Comment by pkarneliuk** [comment]
generally, if you want to hack something - you have to do it yourself.

**Comment by pkarneliuk** [comment]
The tool [ld-config](http://linux.die.net/man/8/ldconfig) helps you to configure your ld.so to look in correct directory for analysis modules
