### ISSUE TITLE
Tests fail on sparc64 and x32 (version 0.4.2)

### ISSUE THREAD

**Issue by andrewshadura** [epam/nfstrace#19]
Aaron M. Ucko [reports](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832069) [multiple](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=sparc64&ver=0.4.2-1&stamp=1469094081) [test failures](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=x32&ver=0.4.2-1&stamp=1469058644) on sparc64 and x32:
oth builds reported

The following tests FAILED:

          1 - functional_stat:1-packet.pcap.bz2 (Failed)
          2 - functional_drain:1-packet.pcap.bz2 (Failed)
          4 - functional_stat:2sessions-tcp-wsize32k-tcp-wsize512k.pcap.bz2 (Failed)
          5 - functional_drain:2sessions-tcp-wsize32k-tcp-wsize512k.pcap.bz2 (Failed)
          7 - functional_stat:eth-ipv4-tcp-cifs2.pcap.bz2 (Failed)
          8 - functional_drain:eth-ipv4-tcp-cifs2.pcap.bz2 (Failed)
         10 - functional_stat:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2 (Failed)
         11 - functional_drain:eth-ipv4-tcp-nfsv3-4-41-cifs1-2.pcap.bz2 (Failed)
         13 - functional_stat:eth-ipv4-tcp-nfsv3-4-readdir-75k-entries.pcap.bz2 (Failed)
         14 - functional_drain:eth-ipv4-tcp-nfsv3-4-readdir-75k-entries.pcap.bz2 (Failed)
         16 - functional_stat:eth-ipv4-tcp-nfsv3.pcap.bz2 (Failed)
         17 - functional_drain:eth-ipv4-tcp-nfsv3.pcap.bz2 (Failed)
         19 - functional_stat:eth-ipv4-tcp-nfsv4-incorrect_mount.pcap.bz2 (Failed)
         20 - functional_drain:eth-ipv4-tcp-nfsv4-incorrect_mount.pcap.bz2 (Failed)
         22 - functional_stat:eth-ipv4-tcp-nfsv4-posix.pcap.bz2 (Failed)
         23 - functional_drain:eth-ipv4-tcp-nfsv4-posix.pcap.bz2 (Failed)
         25 - functional_stat:eth-ipv4-tcp-nfsv4.pcap.bz2 (Failed)
         26 - functional_drain:eth-ipv4-tcp-nfsv4.pcap.bz2 (Failed)
         28 - functional_stat:eth-ipv4-tcp-nfsv41.pcap.bz2 (Failed)
         29 - functional_drain:eth-ipv4-tcp-nfsv41.pcap.bz2 (Failed)
         31 - functional_stat:eth-ipv4-tcp-smb2-putty.pcap.bz2 (Failed)
         32 - functional_drain:eth-ipv4-tcp-smb2-putty.pcap.bz2 (Failed)
         34 - functional_stat:eth-ipv4-tcp-smb2-zero-file-rw.pcap.bz2 (Failed)
         35 - functional_drain:eth-ipv4-tcp-smb2-zero-file-rw.pcap.bz2 (Failed)
         37 - functional_stat:eth-ipv4-udp-nfsv3-dup-retransm.pcap.bz2 (Failed)
         38 - functional_drain:eth-ipv4-udp-nfsv3-dup-retransm.pcap.bz2 (Failed)
         40 - functional_stat:eth-ipv4-udp-nfsv3-reply-first.pcap.bz2 (Failed)
         41 - functional_drain:eth-ipv4-udp-nfsv3-reply-first.pcap.bz2 (Failed)
         43 - functional_stat:eth-ipv4-udp-nfsv3.pcap.bz2 (Failed)
         44 - functional_drain:eth-ipv4-udp-nfsv3.pcap.bz2 (Failed)
         46 - functional_stat:eth-ipv6-tcp-nfsv3-bad_alloc.pcap.bz2 (Failed)
         47 - functional_drain:eth-ipv6-tcp-nfsv3-bad_alloc.pcap.bz2 (Failed)
         49 - functional_stat:eth-ipv6-tcp-nfsv3.pcap.bz2 (Failed)
         50 - functional_drain:eth-ipv6-tcp-nfsv3.pcap.bz2 (Failed)
         52 - functional_stat:lo-ipv4-tcp-nfsv3-nfsacl.pcap.bz2 (Failed)
         53 - functional_drain:lo-ipv4-tcp-nfsv3-nfsacl.pcap.bz2 (Failed)
         55 - functional_stat:tcp-seq-overlap-in-fragment-12721.pcap.bz2 (Failed)
         56 - functional_drain:tcp-seq-overlap-in-fragment-12721.pcap.bz2 (Failed)

and the x32 build additionally reported

         59 - unit_test_parse (SEGFAULT)

For more details, see [Debian bug #832069](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832069)

**Comment by pkarneliuk** [comment]
I have checked [build logs ](https://buildd.debian.org/status/logs.php?pkg=nfstrace). The 4.2.1-1 has failed on [x32](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=x32&ver=0.4.2-1&stamp=1469058644) and [sparc64](https://buildd.debian.org/status/fetch.php?pkg=nfstrace&arch=sparc64&ver=0.4.2-1&stamp=1469094081). The [4.2.1-2 was built successfully](https://buildd.debian.org/status/logs.php?pkg=nfstrace) on all platforms except armel.
Is it fluctuation in build environment or a defect in nfstrace?

**Comment by andrewshadura** [comment]
I haven't checked the logs yet, but I have explicitly added an override to
those two platforms so the build succeeds even when the tests fail.

-- 
Cheers,
  Andrew

**Comment by pkarneliuk** [comment]
I have reproduced these defects on [Debian 3.16.7-ckt11-1+x32+deb8u3 (2015-08-10) x86_64 GNU/Linux](http://debian-x32.org/d-i/netboot-gtk.iso) and fixed then in f9f0349.

@andrewshadura  could you please rerun Debian build environment and verify build on sparc64 and x32?

**Comment by pkarneliuk** [comment]
Hi Andrew,

Is it possible to re-run Debian build infrastructure? It is just a friendly
reminder.


2016-07-30 21:07 GMT+03:00 Andrew Shadura <notifications@github.com>:

> I haven't checked the logs yet, but I have explicitly added an override to
> those two platforms so the build succeeds even when the tests fail.
>
> --
> Cheers,
> Andrew
>

**Comment by andrewshadura** [comment]
It certainly is. However, I'm on a holiday, and doing so requires some
effort from my side I'm not ready to provide now.

-- 
Cheers,
  Andrew

**Comment by pkarneliuk** [comment]
Hi again,

should I create a release for nfstrace on github for fixed bug?

Best regards,
Pavel K

2016-08-01 22:15 GMT+02:00 Andrew Shadura <notifications@github.com>:

> It certainly is. However, I'm on a holiday, and doing so requires some
> effort from my side I'm not ready to provide now.
>
> --
> Cheers,
> Andrew
>
>
