### ISSUE TITLE
Failure to compile on ubuntu 14.04.5 LTS with clang.

### ISSUE THREAD

**Issue by jyelon** [epam/nfstrace#23]
Here's a log of what occurred, with a compile error at the end:

jyelon@jyelon-M4800:~$ echo $CC
/usr/bin/clang
jyelon@jyelon-M4800:~$ echo $CXX
/usr/bin/clang++
jyelon@jyelon-M4800:~$ clang --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
jyelon@jyelon-M4800:~$ git clone https://github.com/epam/nfstrace.git
Cloning into 'nfstrace'...
remote: Counting objects: 12246, done.  
remote: Total 12246 (delta 0), reused 0 (delta 0), pack-reused 12245  
Receiving objects: 100% (12246/12246), 24.54 MiB | 44.78 MiB/s, done.
Resolving deltas: 100% (8710/8710), done.
Checking connectivity... done.
jyelon@jyelon-M4800:~$ cd nfstrace/
jyelon@jyelon-M4800:~/nfstrace$ mkdir release
jyelon@jyelon-M4800:~/nfstrace$ cd release/
jyelon@jyelon-M4800:~/nfstrace/release$ cmake -DCMAKE_BUILD_TYPE=release ../
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- To enable code self-profiling set option PROFILING=ON and build in Release mode
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so - found
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
-- Could NOT find JSON (missing:  JSON_LIBRARY JSON_INCLUDE_DIR) 
CMake Warning at analyzers/src/json/CMakeLists.txt:16 (message):
  JSON library not found - JSON analyzer plugin is not available!

CMake Warning at tests/unit/CMakeLists.txt:2 (message):
  GTEST_SOURCE_DIR variable not set - unit-tests are not available.  Use

```
  '-DGTEST_SOURCE_DIR=<path_to_nfstrace>/third_party/googletest' param for CMake
```

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jyelon/nfstrace/release
jyelon@jyelon-M4800:~/nfstrace/release$ make
Scanning dependencies of target nfstrace
[  1%] Building CXX object CMakeFiles/nfstrace.dir/src/utils/sessions.cpp.o
In file included from /home/jyelon/nfstrace/src/utils/sessions.cpp:22:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/sstream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/istream:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ios:42:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/ios_base.h:41:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/locale_classes.h:40:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
make[2]: **\* [CMakeFiles/nfstrace.dir/src/utils/sessions.cpp.o] Error 1
make[1]: **\* [CMakeFiles/nfstrace.dir/all] Error 2
make: **\* [all] Error 2
jyelon@jyelon-M4800:~/nfstrace/release$

**Comment by michaeljs1990** [comment]
Your version of libstdc++ is not up to date. It's trying to use a c++14 feature which is not available in the version you have currently installed.

This is the environment I used to build this in

```
FROM ubuntu:14.04.5

VOLUME /build
WORKDIR /build

RUN apt-get update \
    && apt-get install -y build-essential \
    automake make libpcap-dev software-properties-common \
    python-software-properties cmake \
    && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
    && apt-get update \
    && apt-get install -y gcc-5 g++-5 \
    && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```

For the runtime dependencies you only need a newer version of libstdc++6 which is available in the ubuntu-toolchain-r/test ppa.
