### ISSUE TITLE
Cannot build with CMake 2.8.12 due to unsupported multi-line comment in FindJSON.cmake

### ISSUE THREAD

**Issue by tripped** [epam/nfstrace#26]
Trying to build with CMake 2.8.12, I get the following error:

```
CMake Error: Error in cmake code at
/home/trip/src/nfstrace/cmake/FindJSON.cmake:22:
Parse error.  Expected "(", got identifier with text "and".
CMake Error at analyzers/src/json/CMakeLists.txt:2 (find_package):
  find_package Error reading CMake code from
  "/home/trip/src/nfstrace/cmake/FindJSON.cmake".
```

Looking at the file in question, it uses a multi-line comment, #[[ ... ]], which is a feature in CMake 3.0 and later. Since README.md indicates that 2.8.12 or later is supported, it might make sense to just revert to single-line comments in that file. It appears to be the only place where multi-line comments are used.

**Comment by pkarneliuk** [comment]
Let's update minimum required version of CMake to 3.0
