### ISSUE TITLE
Build on RHEL/CentOS7

### ISSUE THREAD

**Issue by ybendito** [epam/nfstrace#27]
Hello,
I would like to use the nfstrace on RHEL 7 and do not succeed to build it, as it requests gcc 5.1+ which is not available of RHEL (gcc is 4.8),  clang is also 3.4. I see the nfstrace was tested on CentOS 7, which use the same versions of compiler. 
Can you please provide instruction how to build the tool on such systems?

Thanks,

**Comment by pkarneliuk** [comment]
Hello,
It was tested on CentOS 7 long time ago. Try to hack build scripts for relaxing compiler requirements.
See changes in this commit: https://github.com/epam/nfstrace/commit/23db46d25449c04bbffbed16c17cc5baa3faea62
